version: 2
jobs:
  build:
    working_directory: ~/alembic
    docker:
      - image: circleci/elixir:1.4.5
        environment:
          MIX_ENV: test
    steps:
      - checkout
      - run:
          name: mix-local-hex
          command: mix local.hex --force
      - run:
          name: mix-local-rebar
          command: mix local.rebar --force

      # mix-deps-get with caching

      - restore_cache:
          keys:
            - deps-{{ checksum "mix.lock" }}
            # if `mix deps.get` changes `mix.lock`, then this one should still apply
            - deps-{{ checksum "mix.exs" }}
            # any previous branches deps
            - deps

      - run:
          name: mix-deps-get
          command: mix deps.get --only test

      # in case `mix.exs` has changed because of a requirement change
      - save_cache:
          key: deps
          paths:
            - deps
      # in case `mix.lock` is updated by `mix deps.get`
      - save_cache:
          key: deps-{{ checksum "mix.exs" }}
          paths:
            - deps
      - save_cache:
          key: deps-{{ checksum "mix.lock" }}
          paths:
            - deps

      # mix-compile with caching

      - restore_cache:
          keys:
            - mix-compile-{{ .Environment.OTP_VERSION }}-{{ .Environment.ELIXIR_VERSION }}-{{ checksum "mix.lock" }}
            - mix-compile-{{ .Environment.OTP_VERSION }}-{{ .Environment.ELIXIR_VERSION }}-{{ checksum "mix.exs" }}
            - mix-compile-{{ .Environment.OTP_VERSION }}-{{ .Environment.ELIXIR_VERSION }}

      - run:
          name: mix-compile
          command: mix compile

      - save_cache: &mix_compile_save_cache
          key: mix-compile-{{ .Environment.OTP_VERSION }}-{{ .Environment.ELIXIR_VERSION }}-{{ checksum "mix.lock" }}
          paths:
            # compiled deps, compiled project, and deps PLT
            - _build
            # erlang and erlang+elixir PLTs
            - /home/circleci/.mix
      - save_cache:
          <<: *mix_compile_save_cache
          key: mix-compile-{{ .Environment.OTP_VERSION }}-{{ .Environment.ELIXIR_VERSION }}-{{ checksum "mix.exs" }}
      - save_cache:
          <<: *mix_compile_save_cache
          key: mix-compile-{{ .Environment.OTP_VERSION }}-{{ .Environment.ELIXIR_VERSION }}
      # `mix compile` picking up need for recompile is NOT guaranteed when the Erlang or Elixir version changes, so
      # don't have a general `mix-compile-{{ .Environment.OTP_VERSION }}` or `mix-compile` key

      - run:
          name: mix-coveralls-circle
          command: mix coveralls.circle
      - store_test_results:
          path: _build/test/lib/alembic
      # so test results show up as downloadable artifacts
      - store_artifacts:
          path: _build/test/lib/alembic
          destination: Elixir
      - run:
          name: mix-dialyze-no-analyze
          command: mix dialyze --no-analyse
      - run:
          name: mix-dialyze
          command: mix dialyze
      - run:
          name: mix docs
          command: |
            mix docs 2>&1 | tee mix-docs.txt
            if grep "Closing unclosed backquotes" mix-docs.txt; then exit 1; fi
      - run:
          name: mix-inch-report
          command: mix inch.report
